# -*- coding: utf-8 -*-
"""Sleep health and lifestyle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyNg1hHguArpAsrP7e1rg4L_sUcvnhZL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_csv("/content/Sleep_health_and_lifestyle_dataset.csv")
df

df.info()

d=df.groupby(by=['Gender']).agg({'Sleep Duration':'mean'}).reset_index()
fig = px.pie(d, values='Sleep Duration', names='Gender', title='Sleep Duration by Gender')
fig.update_layout(width=400, height=400)
fig.show()

df1 = df.groupby('Gender').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['Gender'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='Gender', y='Value', color='Attribute',
             title='Sleep Analysis by Gender',
             labels={'Value': 'Average Values', 'Gender': 'Gender', 'Attribute': 'Attributes'},
             height=500, width=700,
             barmode='group')

fig.show()

df1 = df.groupby('Occupation').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['Occupation'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='Occupation', y='Value', color='Attribute',
             title='Sleep Analysis by Occupation',
             labels={'Value': 'Average Values', 'Occupation': 'Occupation', 'Attribute': 'Attributes'},
             height=500, width=900,
             barmode='group')

fig.show()

df1 = df.groupby('Age').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['Age'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='Age', y='Value', color='Attribute',
             title='Sleep Analysis by Age',
             labels={'Value': 'Average Values', 'Age': 'Age', 'Attribute': 'Attributes'},
             height=500, width=1100,
             barmode='group')

fig.show()

df1 = df.groupby('BMI Category').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['BMI Category'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='BMI Category', y='Value', color='Attribute',
             title='Sleep Analysis by BMI Category',
             labels={'Value': 'Average Values', 'BMI Category': 'BMI Category', 'Attribute': 'Attributes'},
             height=500, width=700,
             barmode='group')

fig.show()

df1 = df.groupby('Heart Rate').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['Heart Rate'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='Heart Rate', y='Value', color='Attribute',
             title='Sleep Analysis by Heart Rate',
             labels={'Value': 'Average Values', 'Heart Rate': 'Heart Rate', 'Attribute': 'Attributes'},
             height=500, width=900,
             barmode='group')

fig.show()

df1 = df.groupby('Sleep Disorder').agg({
    'Sleep Duration': 'mean',
    'Quality of Sleep': 'mean',
    'Stress Level': 'mean'
}).reset_index()

df2 = pd.melt(df1, id_vars=['Sleep Disorder'],
                  value_vars=['Sleep Duration', 'Quality of Sleep', 'Stress Level'],
                  var_name='Attribute', value_name='Value')

fig = px.bar(df2, x='Sleep Disorder', y='Value', color='Attribute',
             title='Sleep Analysis by Sleep Disorder',
             labels={'Value': 'Average Values', 'Sleep Disorder': 'Sleep Disorder', 'Attribute': 'Attributes'},
             height=500, width=700,
             barmode='group')

fig.show()

"""Reference plots"""

d=df.groupby(by=['Gender']).agg({'Sleep Duration':'mean'}).reset_index()
fig=px.bar(d,x='Gender',y='Sleep Duration',color='Sleep Duration',title='Sleep Duration by Gender')
fig.update_layout(width=500, height=500)
fig.show()

d=df.groupby(by=['Occupation']).agg({'Sleep Duration':'mean'}).reset_index()
fig=px.bar(d,x='Occupation',y='Sleep Duration',color='Sleep Duration',title='Sleep Duration by Occupation')
fig.update_layout(width=900, height=500)
fig.show()

d=df.groupby(by=['Occupation']).agg({'Quality of Sleep':'mean'}).reset_index()
fig=px.bar(d,x='Occupation',y='Quality of Sleep',color='Quality of Sleep',title='Quality of Sleep by Occupation')
fig.update_layout(width=900, height=500)
fig.show()

d=df.groupby(by=['Occupation']).agg({'Stress Level':'mean'}).reset_index()
fig=px.bar(d,x='Occupation',y='Stress Level',color='Stress Level',title='Stress Level by Occupation')
fig.update_layout(width=900, height=500)
fig.show()

d = df.groupby(by=['Age']).agg({'Sleep Duration': 'mean'}).reset_index()
fig = px.line(d, x='Age', y='Sleep Duration', title='Sleep Duration by Age')
fig.update_layout(width=800, height=500)
fig.show()

